### PR TITLE
support for utf8 characters

### PR DESCRIPTION
**Pull request by bumi**
Currently no UTF8 characters are not supported.
I've changed to use a normal GET parameter which solves this problem.

But that means this changes the API, currently to: /fuck-yeah?q=[your-query]

I haven't found a solution how to fix this in node-router. What do you think?

### CODE REVIEW

**Comment by holman** [comment]
I'm really not a huge fan of changing the API (particularly since we'd have to change our code, simple as that may be). fuck-yeah/fuck-yeah seems redundant, too.

**Comment by bumi** [comment]
me neither,
but I was more unhappy about the UTF8 problems (since umlauts and co are everywhere in german ;) )
do you have an idea concerning the special chars? if I find some time I will investigate some more.

**Comment by holman** [comment]
Not really. This is one of the cases where things work well enough for us and it's such a fly-by-night-project that I'm less concerned with tackling it.

**Comment by bumi** [comment]
yeah, same here. ;) thanks fo sharing brought lot's of laughs to our team

**Pull request closed without merging**
