### PR TITLE
Making text autoresize

### PR DESCRIPTION
**Pull request by jesseditson**
Modified the script to add text to the bottom of the image (I can remove this if it's unneeded), and autosize the text to the image.

### CODE REVIEW

**Comment by holman** [comment]
Mind posting an example? Easier to visualize then.

**Comment by jesseditson** [comment]
Found some issues with small images. They're fixed in that last commit.

here are some images - large ones:

http://imageshack.us/photo/my-images/849/anextremelylongsentance.jpg/
http://imageshack.us/photo/my-images/818/peterpanm.jpg/

small ones:

http://imageshack.us/photo/my-images/833/ducksb.jpg/
http://imageshack.us/photo/my-images/190/slothsv.jpg/

**Comment by holman** [comment]
rad!

**Comment by holman** [comment]
Hrm. Getting:

```
2012-04-10T06:32:23+00:00 heroku[router]: Error H13 (Connection closed without response) -> GET fuckyeah.herokuapp.com/ramen dyno=web.1 queue= wait= service= status=503 bytes=
2012-04-10T06:32:23+00:00 app[web.1]: 
2012-04-10T06:32:23+00:00 app[web.1]:       var h = features.height < 100 ? features.height : 100
2012-04-10T06:32:23+00:00 app[web.1]: /app/index.js:74
2012-04-10T06:32:23+00:00 app[web.1]:                       ^
2012-04-10T06:32:23+00:00 app[web.1]: TypeError: Cannot read property 'height' of undefined
2012-04-10T06:32:23+00:00 app[web.1]:     at /app/index.js:74:23
2012-04-10T06:32:23+00:00 app[web.1]:     at /app/node_modules/imagemagick/imagemagick.js:105:5
```

**Comment by jesseditson** [comment]
hmm, works well locally - features should be the response from imagemagick's `.identify`

**Comment by jesseditson** [comment]
are dependencies up to date?

**Comment by holman** [comment]
Yeah, I'm at 0.1.2 of node-imagemagick.

**Comment by holman** [comment]
Works locally fine. Hrm.

**Comment by jesseditson** [comment]
stuck on a server and reproduced. suspect the error just needs to be caught, commit coming.

**Comment by holman** [comment]
The weird part is on a redeploy Heroku is fine, and then when I try it in Campfire it just dies. It's like the oodles of machines loading the image at once kills node. Maybe node can't scale!

**Comment by holman** [comment]
Yeah, you can reproduce it locally if you just refresh a whole bunch of times in a row. Wonder if that tempfile is the culprit.

(Edit: ah, it's a random tempfile anyway. So who knows.)

**Comment by jesseditson** [comment]
nope, looks like the error I reproduced was caused by imagemagick not being installed - is the 'identify' command installed?

**Comment by holman** [comment]
Yeah, it all works properly locally and in production, but for some reason if you access it frequently it bombs out.

**Comment by holman** [comment]
I don't really understand it, but 177423e5ba68246657b485f9160a3ad149546939 seems to have fixed it maybe. Which is really strange.

**Comment by jesseditson** [comment]
haha - interesting. lmk if it freaks out again!

**Pull request merged**
